# -*- coding: utf-8 -*-
"""JornadaPythonFaixaPretaAula3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R8P_zOvMPXfBq6jYpnBHcPEZ-4UmVETa

#Condicionais

Principal forma de atribuir uma lógica ao seu código.

Basicamente é uma tomada de decisão caso a condição seja verdadeira.

Ex:

- Se o dia estiver quente;
  - Vou tomar um sorvete
  - Vou para a praia

- Do contrário (se não):
  - Comer um chocolate
  - Maratonar Netflix
"""

temperatura = "quente"

print(temperatura)

if temperatura == 'quente':
  print("vou tomar um sorvete de Flocos")
  print("Vou para a praia(mentira, aqui não tem praia)")
else:
  print("Vou comer um chocolate")
  print("Vamos assistir Cobra Kai")

horario = 'noite'

if horario == 'manhã':
  print("O sol está quente")
elif horario == 'tarde':
  print('O por do sol está chegando')
else:
  print("A lua está linda")
  print('Está na hora da jornada Python Faixa Preta')

idade = 17

if idade >=18:
  print('Você já pode beber, mas com moderação')
else:
  print('Você não pode beber')

temperatura = 37

if temperatura <= 30:
  print('Aceitável')
else:
  print('Socorro está muito quente')

altura = 1.75

if altura < 1.80:
  print("O Gean é baixinho")
else:
  print('O Gean é alto')

quente = True
gosta_praia = True
gosta_chocolate_quente = True

if quente == True:
  print('Está quente')
  if gosta_praia == True:
    print('Vá para a praia')
  else:
    print('Não vá a praia')
else:
  print('Está frio')
  if gosta_chocolate_quente == True:
    print('Tome um chocolate quente')
  else:
    print('Não tome chocolate quente')

dia = input('Que dia é hoje? ')

if dia == 'sabado':
  print('É fim de semana :)')
elif dia == "domingo":
  print("É fim de semana :)")
else:
  print('Nao é fim de semana :(')

# 1, 3, 6 e 10 => válido
# qualquer outro => inválido

numero=8

if numero == 1:
  print('é valido')
elif numero == 3:
  print('é valido')
elif numero == 6:
  print('é valido')
elif numero == 10:
  print('é valido')
else:
  print('é invalido')

numero = 8
if numero == 1 or 3 or 6 or 10:
  print('é valido')
else:
  print('é invalido')

meu_nome = 'Gean'
nome = input('Digite seu nome: ')

meu_sobrenome = 'Zambanini'
sobrenome = input('Digite seu sobrenome: ')

apelido = 'Floifer'

if (nome == meu_nome and sobrenome == meu_sobrenome):
  print('Você é o Gean Zambanini"')
else:
  print('Você não é o Gean Zambanini')

for numero in range(1,10):
  print(numero)

for numero in range(10):
  print(numero)

for numero in range(1,11):
  print('O numero atual é:', numero)

notas = [6, 7.5, 9, 10, 3, 5, 10]

soma = 0

for nota in notas:
  soma = soma + nota

print('A soma é ', soma)

media = soma / len(notas)

print('A media é', media)

nomes = ['Felipe','Pedro','Ghéssica','Rafael']
len(nomes)

#Definindo a função
def nome_funcao():
  #Código da função
  print('Código da função')

#Chamando a função
nome_funcao()

def mostrar_nome():
  print('Gean Zambanini')
  print('Floifer')

mostrar_nome()

def mostrar_nome(nome_atual):
  print(nome_atual)

mostrar_nome('Edgar')
mostrar_nome('Fabiana')
mostrar_nome('Paulo')
mostrar_nome('Katia')

def calcular_media(nota1,nota2):
  soma = nota1 + nota2
  media = soma / len(soma)
  print(media)

primeira_nota = float(input('Sua primeira nota: '))
segunda_nota = float(input('Sua segunda nota: '))
  
calcular_media(primeira_nota, segunda_nota)

#IMC => Peso(KG) / Altura(M) ao quadrado.

def numero_quadrado(numero):
  quadrado = numero * numero
  return quadrado

def calcular_imc(peso, altura):
  altura_quadrada = numero_quadrado(altura)
  meu_imc = peso / altura_quadrada

  return meu_imc

def classificar_imc(meu_imc):
  if imc < 18.5:
    print('Magreza')
  elif imc >= 18.5 and imc < 25:
    print('Normal')
  elif imc >= 25 and imc < 30:
    print('Sobrepeso')
  elif imc >= 30 and imc < 40:
    print('Obesidade')
  else:
    print('Obesidade Grave')

imc = calcular_imc(73,1.77)
print('Seu imc é: ', imc)

print('Sua classificação é: ', classificar_imc)

